version: "3.8"

services:
  host-nginx:
    image: nginx:latest
    container_name: host_nginx
    restart: always
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./certs:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
